2022/10  --  Felix Klotzsche

This is a pretty dirty NB that I used to manually check problematic raw files and did some sanity checks. Probably not helpful in the current state but might have some useful snippets, so I keep it.

In [1]:
import os
from os import path as op
from pathlib import Path
import numpy as np
import pandas as pd

from logging import exception, warning

import mne
import mne_bids
from mne_bids import BIDSPath
from vr2fem_analyses.staticinfo import VR2FEMPATHS as PATHS

In [14]:
subID_problematic = ['VR2FEM_S03']
sub_path = Path('..', 'Data', 'Subjects')
sub_list_str = os.listdir(sub_path)
mega_df = pd.DataFrame(columns=['id'])
ev_coll = dict()
for subID in sub_list_str:
    if subID in subID_problematic: continue
    p_data = Path('..', 'Data', 'Subjects', subID, 'MainTask', 'EEG')
    fname = Path(p_data, subID + '.vhdr')
    raw = mne.io.read_raw_brainvision(fname, preload=False, verbose=False)
    evs, ev_dict = mne.events_from_annotations(raw, verbose=False)
    ev_coll[subID] = evs
    df = pd.DataFrame(evs, columns=['time', 'dur', 'id'])
    df = df.groupby('id').size().reset_index(name=subID)
    # df = df[(df['id']>110) & (df['id']<235)]
    if np.any(df.loc[(df['id']>110) & (df['id']<235), subID] != 31):
        mega_df = pd.merge(mega_df, df, how='outer')

In [29]:
mega_df

,id,VR2FEM_S12,VR2FEM_S18,VR2FEM_S23,VR2FEM_S21,VR2FEM_S27,VR2FEM_S26,VR2FEM_S02,VR2FEM_S16,VR2FEM_S29,VR2FEM_S32,VR2FEM_S06,VR2FEM_S24,VR2FEM_S19,VR2FEM_S34,VR2FEM_S09
0,11,747.0,745.0,743.0,746.0,748.0,749.0,144.0,744.0,746.0,741.0,741.0,745.0,743.0,144.0,425.0
1,13,747.0,745.0,743.0,746.0,748.0,749.0,144.0,744.0,746.0,742.0,741.0,745.0,743.0,144.0,424.0
2,14,744.0,740.0,733.0,739.0,740.0,744.0,143.0,730.0,724.0,739.0,736.0,739.0,741.0,142.0,415.0
3,15,3.0,5.0,10.0,7.0,8.0,5.0,1.0,14.0,22.0,2.0,6.0,6.0,3.0,2.0,9.0
4,16,747.0,745.0,742.0,746.0,748.0,749.0,144.0,744.0,746.0,742.0,741.0,745.0,744.0,144.0,424.0
5,111,31.0,31.0,31.0,31.0,31.0,32.0,6.0,31.0,31.0,31.0,31.0,32.0,31.0,6.0,18.0
6,112,32.0,31.0,30.0,31.0,32.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,18.0
7,113,31.0,31.0,31.0,32.0,31.0,32.0,6.0,31.0,31.0,30.0,30.0,31.0,31.0,6.0,16.0
8,114,32.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,30.0,31.0,31.0,6.0,17.0
9,121,31.0,31.0,31.0,31.0,32.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,19.0
10,122,31.0,31.0,30.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,17.0
11,123,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,17.0
12,124,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,17.0
13,131,31.0,31.0,30.0,31.0,32.0,31.0,6.0,31.0,31.0,31.0,30.0,31.0,32.0,6.0,17.0
14,132,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,32.0,6.0,17.0
15,133,31.0,31.0,31.0,31.0,31.0,31.0,6.0,32.0,31.0,31.0,31.0,31.0,31.0,6.0,18.0
16,134,31.0,31.0,32.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,30.0,6.0,18.0
17,211,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,30.0,6.0,20.0
18,212,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,17.0
19,213,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,32.0,31.0,31.0,31.0,31.0,6.0,19.0
20,214,31.0,31.0,32.0,31.0,31.0,31.0,6.0,31.0,31.0,30.0,31.0,31.0,31.0,6.0,17.0
21,221,31.0,31.0,31.0,31.0,31.0,32.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,18.0
22,222,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,18.0
23,223,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,30.0,31.0,31.0,31.0,6.0,20.0
24,224,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,17.0
25,231,32.0,31.0,31.0,31.0,32.0,32.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,19.0
26,232,31.0,31.0,31.0,32.0,31.0,32.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,17.0
27,233,31.0,31.0,31.0,31.0,31.0,31.0,6.0,31.0,31.0,31.0,31.0,31.0,31.0,6.0,16.0
28,234,31.0,32.0,31.0,31.0,31.0,31.0,6.0,31.0,32.0,31.0,31.0,31.0,30.0,6.0,18.0
29,10001,1.0,1.0,9.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,16.0,1.0
30,10002,1.0,NaN,3.0,2.0,1.0,1.0,NaN,1.0,NaN,1.0,2.0,1.0,1.0,6.0,1.0
31,10003,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN
32,99999,3.0,4.0,6.0,1.0,3.0,2.0,1.0,3.0,2.0,3.0,1.0,3.0,3.0,1.0,4.0
33,10,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,10004,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN
35,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
36,10005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN
37,10006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN
38,10007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN

In [13]:
paths = PATHS()
subID = 'VR2FEM_S19'

eeg_data = Path(paths.DATA_SUBJECTS, subID, 'MainTask', 'EEG')
fname1 = Path(eeg_data, subID + '.vhdr')
raw1 = mne.io.read_raw_brainvision(fname1, preload=True,       
                                    verbose=False)

evs, ev_dict = mne.events_from_annotations(raw1, verbose=False)
df = pd.DataFrame(evs, columns=['time', 'dur', 'id'])
df = df.groupby('id').size().reset_index(name=subID)
df

       id  VR2FEM_S19
0      11         743
1      13         743
2      14         741
3      15           3
4      16         744
5     111          31
6     112          31
7     113          31
8     114          31
9     121          31
10    122          31
11    123          31
12    124          31
13    131          32
14    132          32
15    133          31
16    134          30
17    211          30
18    212          31
19    213          31
20    214          31
21    221          31
22    222          31
23    223          31
24    224          31
25    231          31
26    232          31
27    233          31
28    234          30
29  10001           1
30  10002           1
31  10003           1
32  10004           1
33  10005           1
34  10006           1
35  10007           1
36  99999           3

In [17]:
subID = 'VR2FEM_S23'
eeg_data = Path(paths.DATA_SUBJECTS, subID, 'MainTask', 'EEG')
fname1 = Path(eeg_data, subID + '.vhdr')
raw1 = mne.io.read_raw_brainvision(fname1, preload=True,       
                                verbose=False)
# delete first 2 events & we lost some events due to bad connection:
n_ev2skip = 2
counter = 0
idx_del = []
for idx, a in enumerate(raw1.annotations):
    sdesc = a['description']
    if 'Stimulus' in sdesc and counter < n_ev2skip:
        idx_del.append(idx)
        if sdesc == 'Stimulus/S 16': # trial end
            counter += 1
raw1.annotations.delete(idx_del)

In [56]:
ev23, ed = mne.events_from_annotations(raw1, verbose=False)
idx_stims = (ev23[:,2] > 100) & (ev23[:,2] <400)
stims23 = ev23[idx_stims,2]

ftres = Path(paths.DATA_SUBJECTS, subID, 'MainTask', 'Unity', 'S001', 'trial_results.csv')
tres23 = pd.read_csv(ftres)
start_prob = np.where(np.array(tres23['marker'])[:len(stims23)] != 
                      stims23)[0][0]

compare = np.array([np.array(tres23['marker'])[:len(stims23)], stims23])
compare[:, start_prob-5:].T
stims23_1 = np.insert(stims23, start_prob, 112)
compare_1 = np.array([np.array(tres23['marker'])[:len(stims23_1)], stims23_1])
start_prob_1 = np.where(compare_1[0,:] != compare_1[1,:])[0][0]
compare_1[:, start_prob_1-5:].T
stims23_2 = np.insert(stims23_1, start_prob_1, [122, 131])
np.all(stims23_2 == tres23['marker'])
print(start_prob)
print(start_prob_1)

208
610

In [4]:
# sub S32
paths = PATHS()
subID = 'VR2FEM_S32'
eeg_data = Path(paths.DATA_SUBJECTS, subID, 'MainTask', 'EEG')
fname1 = Path(eeg_data, subID + '.vhdr')
raw1 = mne.io.read_raw_brainvision(fname1, preload=True,       
                                verbose=False)
ev32, ed = mne.events_from_annotations(raw1, verbose=False)
idx_stims = (ev32[:,2] > 100) & (ev32[:,2] <400)
stims32 = ev32[idx_stims,2]

ftres32 = Path(paths.DATA_SUBJECTS, subID, 'MainTask', 'Unity', 'S001', 'trial_results.csv')
tres32 = pd.read_csv(ftres32)


compare = np.array([np.array(tres32['marker'])[:len(stims32)], stims32])
start_prob = np.where(compare[0,:] != compare[1,:])[0][0]
print(start_prob)
aa = compare.T

In [7]:
# sub S06
paths = PATHS()
subID = 'VR2FEM_S06'
eeg_data = Path(paths.DATA_SUBJECTS, subID, 'MainTask', 'EEG')
fname1 = Path(eeg_data, subID + '.vhdr')
raw1 = mne.io.read_raw_brainvision(fname1, preload=True,       
                                verbose=False)
ev06, ed = mne.events_from_annotations(raw1, verbose=False)
idx_stims = (ev06[:,2] > 100) & (ev06[:,2] <400)
stims06 = ev06[idx_stims,2]

/tmp/ipykernel_68852/599434576.py:15: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.any(level=1) should use df.groupby(level=1).any()
  ha = tres06[tres06.stack().str.contains('Stimulus Onset').any(level=0)]

        0
1     221
6     123
11    122
16    113
21    223
...   ...
3696  131
3701  231
3706  223
3711  132
3716  132

[744 rows x 1 columns]

In [17]:

ftres06 = Path(paths.DATA_SUBJECTS, subID, 'MainTask', 'Unity', 'S001', 'other','markerLog.csv')
tres06 = pd.read_csv(ftres06)
tres06
ha = tres06[tres06.stack().str.contains('Stimulus Onset').any(level=0)]
mrkrs = ha.annotation.str.extract('(\d+)')
mrkrs.columns = ['marker']
mrkrs_i = pd.to_numeric(mrkrs.marker)

/tmp/ipykernel_68852/74431647.py:4: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.any(level=1) should use df.groupby(level=1).any()
  ha = tres06[tres06.stack().str.contains('Stimulus Onset').any(level=0)]

1        True
6       False
11      False
16      False
21      False
        ...
3696    False
3701    False
3706    False
3711    False
3716    False
Name: marker, Length: 744, dtype: bool

In [19]:

compare = np.array([np.array(mrkrs_i)[:len(stims06)], stims06])
start_prob = np.where(compare[0,:] != compare[1,:])[0][0]
print(start_prob)
aa = compare.T

610



subID = 'VR2FEM_S19'
sub_evs = ev_coll[subID]

# check whether every stim onset is followed by a stim offset event:
idx_stimon = np.where((sub_evs[:,2]>110) & (sub_evs[:,2]<235))
if (np.any(sub_evs[idx_stimon[0] + 1, 2] != 13)):
    raise ValueError(f'{subID}:    NOt each stim onset followed by offset event.')

stim_onsets = sub_evs[idx_stimon, :]
stim_offsets = sub_evs[(sub_evs[:,2]==13), :]
if (len(stim_onsets) != len(stim_offsets)): 
    raise ValueError(f'{subID}:    Unequal number of stim on- and offsets.')
diffs = (stim_offsets[:,0] - stim_onsets[:,0])  # [:-1,0])



idx = np.where(sub_evs[:,0] == stim_onsets[631,0])
sub_evs[idx[0][0]-10:idx[0][0]+10]
diffs[np.where(diffs > 510)]
#diffs

In [15]:
idx_stimon[0] +1

array([   4,    9,   14,   19,   24,   29,   34,   39,   45,   50,   55,
         60,   65,   70,   75,   80,   85,   90,   95,  100,  105,  110,
        115,  120,  125,  130,  135,  140,  145,  150,  155,  160,  165,
        170,  175,  180,  185,  190,  195,  200,  205,  210,  215,  220,
        225,  230,  236,  241,  246,  251,  256,  261,  266,  271,  276,
        281,  286,  291,  296,  301,  306,  311,  316,  321,  326,  331,
        336,  341,  346,  351,  356,  361,  366,  371,  376,  381,  386,
        391,  396,  401,  406,  411,  416,  421,  426,  431,  436,  441,
        446,  451,  456,  461,  467,  472,  477,  482,  487,  492,  497,
        502,  507,  512,  517,  522,  527,  532,  537,  542,  547,  552,
        557,  562,  567,  572,  577,  582,  587,  592,  597,  602,  607,
        612,  617,  622,  627,  632,  637,  642,  647,  652,  657,  662,
        667,  672,  677,  682,  687,  692,  697,  702,  707,  712,  717,
        722,  727,  732,  737,  742,  747,  752,  757,  762,  767,  772,
        777,  782,  787,  792,  797,  802,  807,  812,  817,  822,  827,
        832,  837,  842,  847,  852,  857,  862,  867,  872,  877,  882,
        887,  892,  897,  902,  907,  912,  917,  922,  927,  932,  937,
        942,  947,  952,  957,  962,  967,  972,  977,  982,  987,  992,
        997, 1002, 1007, 1012, 1017, 1022, 1027, 1032, 1037, 1042, 1047,
       1052, 1057, 1062, 1067, 1072, 1077, 1082, 1087, 1092, 1097, 1102,
       1107, 1112, 1117, 1122, 1127, 1132, 1137, 1142, 1147, 1152, 1157,
       1162, 1167, 1172, 1177, 1182, 1187, 1192, 1197, 1202, 1207, 1212,
       1217, 1222, 1227, 1232, 1237, 1242, 1247, 1252, 1257, 1262, 1267,
       1272, 1277, 1282, 1287, 1292, 1297, 1302, 1307, 1312, 1317, 1322,
       1327, 1332, 1337, 1342, 1347, 1352, 1357, 1362, 1367, 1372, 1377,
       1382, 1387, 1392, 1397, 1402, 1407, 1412, 1417, 1422, 1427, 1432,
       1437, 1442, 1447, 1452, 1457, 1462, 1467, 1472, 1477, 1482, 1487,
       1492, 1497, 1502, 1507, 1512, 1517, 1522, 1527, 1532, 1537, 1542,
       1547, 1552, 1557, 1562, 1567, 1572, 1577, 1582, 1587, 1592, 1597,
       1602, 1607, 1612, 1617, 1622, 1627, 1632, 1637, 1642, 1647, 1652,
       1657, 1662, 1667, 1672, 1677, 1682, 1687, 1692, 1697, 1702, 1707,
       1712, 1717, 1722, 1727, 1732, 1737, 1742, 1747, 1752, 1757, 1762,
       1767, 1772, 1777, 1782, 1787, 1792, 1797, 1802, 1807, 1812, 1817,
       1822, 1827, 1832, 1837, 1842, 1847, 1852, 1857, 1862, 1867, 1872,
       1877, 1882, 1887, 1892, 1897, 1902, 1907, 1912, 1917, 1922, 1927,
       1932, 1937, 1942, 1947, 1952, 1957, 1962, 1967, 1972, 1977, 1982,
       1987, 1992, 1997, 2002, 2007, 2012, 2017, 2022, 2027, 2032, 2037,
       2042, 2047, 2052, 2057, 2062, 2067, 2072, 2077, 2082, 2087, 2092,
       2097, 2102, 2107, 2112, 2117, 2122, 2127, 2132, 2137, 2142, 2147,
       2152, 2157, 2162, 2167, 2172, 2177, 2182, 2187, 2192, 2197, 2202,
       2207, 2212, 2217, 2222, 2227, 2232, 2237, 2242, 2247, 2252, 2257,
       2262, 2267, 2272, 2277, 2282, 2287, 2292, 2297, 2302, 2307, 2312,
       2317, 2322, 2327, 2332, 2337, 2342, 2347, 2352, 2357, 2362, 2367,
       2372, 2377, 2382, 2387, 2392, 2397, 2402, 2407, 2412, 2417, 2422,
       2427, 2432, 2437, 2442, 2447, 2452, 2457, 2462, 2467, 2472, 2477,
       2482, 2487, 2492, 2497, 2502, 2507, 2512, 2517, 2522, 2527, 2532,
       2537, 2542, 2547, 2552, 2557, 2562, 2567, 2572, 2577, 2582, 2587,
       2592, 2597, 2602, 2607, 2612, 2617, 2622, 2627, 2632, 2637, 2642,
       2647, 2652, 2657, 2662, 2667, 2672, 2677, 2682, 2687, 2692, 2697,
       2702, 2707, 2712, 2717, 2722, 2727, 2732, 2737, 2742, 2747, 2752,
       2757, 2762, 2767, 2772, 2777, 2782, 2787, 2792, 2797, 2802, 2807,
       2812, 2817, 2822, 2827, 2832, 2837, 2842, 2847, 2852, 2857, 2862,
       2867, 2872, 2877, 2882, 2887, 2892, 2897, 2902, 2907, 2912, 2917,
       2922, 2927, 2932, 2937, 2942, 2947, 2952, 2957, 2962, 2967, 2972,
       2977, 2982, 2987, 2992, 2997, 3002, 3007, 3012, 3017, 3022, 3027,
       3032, 3037, 3042, 3047, 3052, 3057, 3062, 3067, 3072, 3077, 3082,
       3087, 3092, 3097, 3102, 3107, 3112, 3117, 3122, 3127, 3132, 3137,
       3142, 3147, 3152, 3157, 3158, 3163, 3168, 3173, 3178, 3183, 3188,
       3193, 3198, 3203, 3208, 3213, 3218, 3223, 3228, 3233, 3238, 3243,
       3248, 3253, 3258, 3263, 3268, 3273, 3278, 3283, 3288, 3293, 3298,
       3303, 3308, 3313, 3318, 3323, 3328, 3333, 3338, 3343, 3348, 3353,
       3358, 3363, 3368, 3373, 3378, 3383, 3388, 3393, 3398, 3403, 3408,
       3413, 3418, 3423, 3428, 3433, 3438, 3443, 3448, 3453, 3458, 3463,
       3468, 3473, 3478, 3483, 3488, 3493, 3498, 3503, 3508, 3513, 3518,
       3523, 3528, 3533, 3538, 3543, 3548, 3553, 3558, 3563, 3568, 3573,
       3578, 3583, 3588, 3593, 3598, 3603, 3608, 3613, 3618, 3623, 3628,
       3633, 3638, 3643, 3648, 3653, 3658, 3663, 3668, 3673, 3678, 3683,
       3688, 3693, 3698, 3703, 3708, 3713, 3718, 3723])

In [57]:
fname = Path(p_data, subID + '.vhdr')
raw = mne.io.read_raw_brainvision(fname, preload=False)

Extracting parameters from ../Data/Subjects/VR2FEM_S28/MainTask/EEG/VR2FEM_S28.vhdr...
Setting channel info structure...

In [62]:

np.sum(evs[0][:,2] == 211)
df = pd.DataFrame(evs[0], columns=['time', 'dur', 'id'])
df.groupby('id').size().reset_index(name='counts')

       id  counts
0      11     744
1      13     744
2      14     742
3      15       2
4      16     744
5     111      31
6     112      31
7     113      31
8     114      31
9     121      31
10    122      31
11    123      31
12    124      31
13    131      31
14    132      31
15    133      31
16    134      31
17    211      31
18    212      31
19    213      31
20    214      31
21    221      31
22    222      31
23    223      31
24    224      31
25    231      31
26    232      31
27    233      31
28    234      31
29  10001       1
30  10002       1
31  10003       1
32  10004       1
33  99999       2

In [24]:
bids_root = Path('..', 'Data', 'bids')
bids_path = BIDSPath(root=bids_root)

In [27]:
os.listdir(bids_path.root)

[]

In [28]:
bids_path.entities

{'subject': None,
 'session': None,
 'task': None,
 'acquisition': None,
 'run': None,
 'processing': None,
 'space': None,
 'recording': None,
 'split': None,
 'description': None}

In [29]:
bids_path

BIDSPath(
root: ../Data/bids
datatype: None
basename: )

In [32]:
print(bids_path.fpath)

FileNotFoundError: [Errno 2] No such file or directory: '../Data/bids/sub-None'